mongodb:
    image: mongo
    expose:
     - 27017
    volumes:
     - /var/mongo/db:/data/db
    restart: unless-stopped
katalog:
    image: joakimbeng/katalog
    expose:
     - 5005
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /var/katalog/data:/app/data
     - /var/katalog/nginx:/app/nginx
    restart: unless-stopped
sitewatcher:
    build: github.com/letterix/nginx-site-watcher.git
    expose:
     - 80
    volumes:
     - /var/katalog/nginx:/etc/nginx/sites-enabled
    restart: unless-stopped
api:
    build: github.com/Softhouse/laughing-batman.git
    links:
     - mongodb
    env_file: github_secret.env
    environment:
     - KATALOG_VHOSTS=default/api
     - MONGO_HOST=mongodb
builder:
    build: github.com/Softhouse/flaming-computing-machine.git
    links:
     - mongodb
     - sitewatcher:xyz
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/bin/docker:/usr/bin/docker
    env_file: github_secret.env
    environment:
     - MONGO_HOST=mongodb
     - SITEWATCHER_HOST=xyz
    restart: unless-stopped
proxy:
    image: nginx
    ports:
     - 80:80
    links:
     - sitewatcher
    volumes:
     - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./proxy/nginx/sites-enabled:/etc/nginx/sites-enabled
    restart: unless-stopped
