mongodb:
    image: dockerfile/mongodb
    expose: 
     -  27017:27017
    volumes:
     -  /var/mongo/db:/data/db
katalog:
    image: joakimbeng/katalog
    expose:
     -  5005:5005
    privileged: true
    volumes: 
     -  /var/run/docker.sock:/var/run/docker.sock
     -  /var/katalog/data:/app/data
     -  /var/katalog/nginx:/app/nginx
#     -  /var/katalog/tpl:/app/tpl
siteWatcher:
    image: joakimbeng/nginx-site-watcher
    expose:
     -  80:8080
    volumes:
     -  /etc/localtime:/etc/localtime:ro
     -  /var/katalog/nginx:/etc/nginx/sites-enabled
     -  /var/log/nginx:/var/log/nginx
builder:
    build: github.com/Softhouse/laughing-batman.git
    links:
     -  mongodb
    env_file: github_secret.env
    environment: 
     -  KATALOG_VHOSTS=default/api
     -  MONGO_HOST=mongodb
api:
    build: github.com/Softhouse/flaming-computing-machine.git
    links:
     -  mongodb
    volumes: 
     -  /var/run/docker.sock:/var/run/docker.sock
     -  /usr/bin/docker:/usr/bin/docker
    env_file: github_secret.env
    environment:
     -  MONGO_HOST=mongodb
googleauth:
    image: a5huynh/google-auth-proxy
    expose: 
     -  4180
    env_file: google_auth_proxy.env
    links:
     -  siteWatcher
#    command: --upstream=http://0.0.0.0:8080/ --http-address=0.0.0.0:4180
proxy:
  image: dockerfile/nginx
  ports:
    - 80:80
  links:
    - googleauth
  volumes:
    - ./configs/nginx/nginx.conf:/etc/nginx.conf
    - ./configs/nginx/sites-enabled:/etc/nginx/sites-enabled
    - /var/log/nginx-proxy:/var/log/nginx
