version: '2'
services:
  consul:
    image: progrium/consul
    restart: unless-stopped
    environment:
      - SERVICE_IGNORE=always
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 53:53
      - 53:53/udp
    command: "-node ${machine_name} -server -advertise ${advertise_ip} -bootstrap expect 2"
  registrator:
    image: gliderlabs/registrator
    command: "-internal -resync 30 consul://${advertise_ip}:8500"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    environment:
      - SERVICE_IGNORE=always
    restart: unless-stopped
